route:
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 20s
  group_by: ['alertname', 'cluster', 'service']
  receiver: alertmanager-bot
 
receivers:
- name: 'alertmanager-bot'
  webhook_configs:
  - send_resolved: true
    url: 'http://alertmanager-bot:8080'
